### ISSUE TITLE
 Server Error (500), when using latin-ext character set

### ISSUE THREAD

**Issue by yochrepi** [xoneco/simple-poll#1]
I get a
 `Simple Poll BOT [10:17] Only you can see this message
<h1>Server Error (500)</h1>` 
response in Slack when using characters like č, š, ž from latin-ext character set.

**Comment by wilhelmklopp** [comment]
Thanks for this!
I applied a fix, and it seems to work for me now. (See screenshot)

![image](https://cloud.githubusercontent.com/assets/7718702/12117351/2a47c8d6-b3b8-11e5-9ab3-b8e18503856f.png)

Please test and see if it works for you :)

**Comment by yochrepi** [comment]
Yes, works beautifully, thnx!

**Comment by wilhelmklopp** [comment]
Cool :)
