### ISSUE TITLE
Icon picking

### ISSUE THREAD

**Issue by mfeola** [xoneco/simple-poll#10]
Is there a way to chose which icons I want to use?  Your example video works well for my request, where if someone asked what's for lunch and you gave them a choice of pizza or burger and they had icons for pizza or burger to click?

**Comment by wilhelmklopp** [comment]
Yeah, this is actually supported since yesterday! Check #4 for more details.

Essentially, you can use the following syntax to replace the respective emojis (the first one in this case):
`/poll "question" "choice one" :robot_face: "choice two"`
