### ISSUE TITLE
smart quotes confuse the app so it makes more options than desired

### ISSUE THREAD

**Issue by JMoVS** [xoneco/simple-poll#12]
Having smart quotes turned on (maybe only on a German system where we write „", viable options are not viable anymore and instead split up at the indiviudal word boundaries.

Probably related to #2

**Comment by wilhelmklopp** [comment]
Hey JMoVS,

Could you post an example query, which doesn't work for you?

**Comment by JMoVS** [comment]
/poll „testing“ „option a“ „option b"

results in "testing"
1: option
2: a
3: option
4: b

**Comment by wilhelmklopp** [comment]
Damn, how has this remained unfixed until now?!?

Will get on this ASAP. Thanks

**Comment by JMoVS** [comment]
Also be careful as the last " isn't smart-treated because replacement is triggered by the space and at the last option, no space is entered.

Do you know what I mean?

**Comment by wilhelmklopp** [comment]
Yes.

Should work now. Can you confirm?

**Comment by JMoVS** [comment]
yes, it works now. Though is it expected behaviour that the text entry box isn't cleared after hitting enter and the poll is created?

**Comment by wilhelmklopp** [comment]
Awesome!

This is the slack default behaviour. It depends entirely on how quickly Simple Poll can respond to the slash command. Am working on improving this at the moment :)

**Comment by JMoVS** [comment]
perfect, thx!
