### ISSUE TITLE
Polling options rearrange themselves after posting the poll

### ISSUE THREAD

**Issue by juc9063** [xoneco/simple-poll#13]
Using Slack (Mac) v2.0.0 (3222), also tested on web and Slack mobile app 

After a poll has been posted, I notice that the emoji options sometimes rearrange themselves from "1-2-3-4-5" to something random eg "5-2-3-1-4".

Is there any way to prevent this from happening?

Thank you!

![poll](https://cloud.githubusercontent.com/assets/17817244/13732093/b7c3bbb6-e950-11e5-99e6-b53933e0d91b.jpg)

**Comment by wilhelmklopp** [comment]
Hey,

So this is a problem that I sadly have no control over. All I can do is send the requests to add emoji reactions to the [endpoint](https://api.slack.com/methods/reactions.add) in the right order. At the moment it is not possible to add multiple emoji reactions in a single request. Also the order or emoji reactions is not very strictly controlled, you just kind of have to hope that the respective clients receive them in the right order.

I have reached out to Slack about both of these potential improvements to the API:

Stay tuned ;) And thanks for the feedback :+1:

**Comment by wilhelmklopp** [comment]
Closing this because button polls (which resolve this issue) are out of beta and fully ready for use 😃
