### ISSUE TITLE
https://simplepoll.rocks/advanced/ page not found.

### ISSUE THREAD

**Issue by AknEp** [xoneco/simple-poll#14]
when I put `/poll test`

bot says:

```
Error: Too few arguments
To create a poll you need to format your query in the following way:
/poll "Is this a poll?" "Yes" "No"
This will create a poll with the question "Is this a poll?", and with the two possible responses "Yes" and "No".
For Advanced options go to https://simplepoll.rocks/advanced/.
```

but, `https://simplepoll.rocks/advanced/` returns 404

**Comment by wilhelmklopp** [comment]
Yes, this is well spotted. Am in the process of re-working the entire page. 

Updates soon :)

**Comment by dsjolie** [comment]
Page still not found... Some time ago now.

**Comment by wilhelmklopp** [comment]
This is fixed now. Instead of /advanced/, the page is https://simplepoll.rocks/faq/ :smiley:

**Comment by AknEp** [comment]
Great! 👍 

Thank you for useful integration. :)
