### ISSUE TITLE
Delete and Edit Polls

### ISSUE THREAD

**Issue by rockymontana** [xoneco/simple-poll#18]
Hello.
I created a Poll in a private channel - that I cannot delete.
The formatting does f*cked and I can't edit or delete the post

**Comment by wilhelmklopp** [comment]
Hey,

Yes, Slack currently restricts deleting of messages. Only admins and owners can do it.
What do you mean with the formatting? Do you have a screenshot?

**Comment by rockymontana** [comment]
I qouted a word in my poll question which became a vote option.
And since Simple Poll sends that message I don't have the access to edit the message (since - it's not my message).
So - the Poll was like this:
/poll "Hello, This is an example "question" that I would like to ask. Do you have an answer?" "Yes" "No"

Programatically I see why it fails, so that's not an issue at all. But it would be nice to be able to tell the Simple Poll bot that the question was incorrect and edit it somehow.

**Comment by wilhelmklopp** [comment]
Yeah, you're right. It's a good point. And there are ways to do this with https://api.slack.com/methods/chat.delete and https://api.slack.com/methods/chat.update. It just needs to be built in the right way. It's definitely on the roadmap though.

**Comment by fatso83** [comment]
Maybe change the name of this issue to reflect that it also involves editing, not just deleting?

**Comment by wilhelmklopp** [comment]
Yes, good point! Thank you :)

**Comment by rockymontana** [comment]
Thanks for clarifying guys!

**Comment by wilhelmklopp** [comment]
This is now a feature :tada: :balloon: 

https://simplepoll.rocks/dashboard

Thank you all for waiting so patiently :smile:

**Comment by rockymontana** [comment]
Thanks a bunch and good job!

**Comment by RobRimmer** [comment]
I still can't see any option to edit my poll (I want to add a "none of the above" option)
