### ISSUE TITLE
Clickable poll options not displayed

### ISSUE THREAD

**Issue by davidstelter** [xoneco/simple-poll#19]
Currently totally broken for us. The options list is displayed but the clickable emoji are not, meaning nobody can actually use the poll.

**Comment by wilhelmklopp** [comment]
Hey, so this seems to be the same problem as #8, except now it actually creates the poll as opposed to just saying that the poll creation fails. Just as before this happens in all private channels and MPIMs that the person installing Simple Poll is not a part of.

Slack is working on adding the feature that will remove this bug at the moment.

However, you _can_ definitely still poll! You just have to add the emoji reactions manually (as shown in the image below)
![Add reactions manually](http://i.imgur.com/zNvSzX0.png)

**Comment by davidstelter** [comment]
Ah, thanks! I didn't review the existing bugs well enough.

**Comment by wilhelmklopp** [comment]
Thank you! Having this as a separate issue is actually a really good idea, and allows people to see the progress :smile:

**Comment by stygiansabyss** [comment]
I have a slightly different issue.  When i create the poll it automatically makes me react with both.  Meaning I cannot vote and both votes start off with a vote of 1.

**Comment by wilhelmklopp** [comment]
Hi @stygiansabyss!

This seems to be related to #3

**Comment by jxc876** [comment]
Seeing the same issue for a while now, the options will be displayed, but there is no way to vote. 

EDIT: Just saw the manual step to add reactions, thanks that helps a bit :)

**Comment by slackint** [comment]
Hello, 
Any news on this topic? We would appreciate the function with automatic emojis, when creating a poll as you documented on your website in the demo video.
Thank you and Regards

**Comment by wilhelmklopp** [comment]
@slackint you may want to try out button polls, which are now in BETA. You can disable them in the dashboard settings. https://simplepoll.rocks/dashboard

![button polls](https://simplepoll.rocks/static/dashboard/images/button-polls.png)

**Comment by wilhelmklopp** [comment]
Closing this because button polls (which resolve this issue) are out of beta and fully ready for use 😃
