### ISSUE TITLE
I think there is a problem with quotes my slack will convert to smart quotes:  " vs “

### ISSUE THREAD

**Issue by mvaneijgen** [xoneco/simple-poll#2]
When I copy your demo it works fine, but when typing it my self I get this `**`.

So if your on OS X you have te disable smart quotes to get it to work. `System Preferences > Keyboard > Text > Uncheck "Use smart quotes and dashes`.

Is that something you can fix? Or do I have to disable smart quotes all the time.

**Comment by jameswragg** [comment]
I'm getting this too. The bot should detect & replace curly-quotes with straight before parsing, it's not acceptable to make the user disable smart quotes in the UI.

**Comment by wilhelmklopp** [comment]
Thanks for the feedback guys :)
It should be fixed now: Unicode characters `201C` and `201D` are automatically converted to `"` now

Please test if it works for you.

**Comment by jameswragg** [comment]
Works for me, thanks!

**Comment by wilhelmklopp** [comment]
Awesome
