### ISSUE TITLE
Link with hash not being properly bolded

### ISSUE THREAD

**Issue by donavon** [xoneco/simple-poll#23]
If I enter this as my poll:

```
/poll http://www.example.com#somehash a b
```

The Simple Poll displays this:
![image](https://cloud.githubusercontent.com/assets/887639/16822537/2b741e04-492b-11e6-9321-660dc4c86ebd.png)

And if you snoop on the line, you see that you (or Slack) incorrectly placed markdown bold around the line as follows (note that the last `*` should be outside of the `>`:

``` js
{ text: '*<http://www.example.com#somehash*>\n\n:one: a\n:two: b',
  username: 'Simple Poll',
  icons: { image_48: 'https://s3-us-west-2.amazonaws.com/slack-files2/bot_icons/2016-07-13/59574127761_48.png' },
  bot_id: 'B1RGP9V8V',
  type: 'message',
  subtype: 'bot_message',
  team: 'T0CK85L68',
  user_team: 'T0CK85L68',
  channel: 'C1PL7RT53',
  ts: '1468450205.000037' }
```

**Comment by wilhelmklopp** [comment]
Just tried this out in completely non-Simple Poll native Slack, and it's the exact same issue there.

You might want to let feedback@slack.com know about this.
