### ISSUE TITLE
Can't seem to delete or modify polls

### ISSUE THREAD

**Issue by pbucci** [xoneco/simple-poll#25]

**Comment by wilhelmklopp** [comment]
Hi, would you be able to provide some more information?

A screenshot and a more accurate description of what is going on?

**Comment by pbucci** [comment]
Hi Wilhelm,

Sorry, dashed off that bug report too quickly. Better description:

After publishing a poll, it seems like it is impossible to retroactively
modify poll questions or title. This itself would be OK if you were able to
delete the polls, but since you cannot, a mistake on a poll hangs around,
people click on the wrong things, it is confusing. It would be best if you
could either modify or delete polls.

Thanks

Paul

Paul Bucci
+1.604.615.3069

**Comment by wilhelmklopp** [comment]
Hi Paul,

You can do this in the Simple Poll dashboard: https://simplepoll.rocks/dashboard/

Best,

Will

**Comment by pbucci** [comment]
Thanks, couldn't find this in the documentation.
—Paul

Paul Bucci
+1.604.615.3069
