### ISSUE TITLE
Update simple-poll to utilize message buttons rather than Emoji

### ISSUE THREAD

**Issue by imjoshdean** [xoneco/simple-poll#26]
https://api.slack.com/docs/message-buttons

Doing this also affords the person who currently is unable to vote in polls due to emojis being used to vote.

**Comment by wilhelmklopp** [comment]
Hi Josh, button polls have been in BETA for a while, and I hope to enable them by default soon. You can enable button polls in the dashboard settings: https://simplepoll.rocks/dashboard/

This is what they look like:
![Button polls](https://simplepoll.rocks/static/dashboard/images/button-polls.png)

**Comment by imjoshdean** [comment]
Thank you so much, totally missed that!
