### ISSUE TITLE
Poll reactions are out of order.

### ISSUE THREAD

**Issue by t-mullen** [xoneco/simple-poll#27]
![screen shot 2016-10-17 at 3 10 39 pm](https://cloud.githubusercontent.com/assets/14932492/19451687/f2d10854-947b-11e6-92a0-5ad1d803e1ca.png)

The reactions appear out of order after a few votes, which is counter-intuitive. (1 should be first, and so on.)

**Comment by t-mullen** [comment]
Duplicate. My bad.

**Comment by wilhelmklopp** [comment]
Yup, this is an issue with how slack deals with storing the order of reactions. At the beginning they're all in the right order and then they mess up over time.

Thankfully this is no longer a problem with button polls :)
See #26
