### ISSUE TITLE
Answer vs Emoji ordering

### ISSUE THREAD

**Issue by slowtree** [xoneco/simple-poll#29]
Hi guys,
it seems that there's a little ordering bug. 
It happens that the order of the emoji reactions at the bottom of the poll frame is different from the one of the answers. 
It's kind of confusing. See the image.

![screen shot 2016-10-20 at 13 56 29](https://cloud.githubusercontent.com/assets/1246790/19558896/29dcc9a2-96cd-11e6-9621-ff73229c9f35.png)

**Comment by wilhelmklopp** [comment]
Hi,

This seems to be a duplicate of #13
