### ISSUE TITLE
Initial reactions come from user

### ISSUE THREAD

**Issue by wilhelmklopp** [xoneco/simple-poll#3]
Simple Poll will initialise the Poll emoji as the user who installed Simple Poll via "Add to Slack".

Ideally, Simple Poll would initialise these reactions itself.
This requires an additional OAuth scope, which the Slack API does not currently provide: `reactions:write:bot`

https://twitter.com/wilhelmklopp/status/684190369429467138

**Comment by wilhelmklopp** [comment]
The reasoning behind the decision of not solving this using a bot-user is explained here: https://www.producthunt.com/tech/simple-poll

**Comment by nicgordon** [comment]
Everyone seems to be suggesting that you ought to have the initial reactions come from a bot, but for the reasons you have given I completely agree with you that that is not the best option. Surely though, the next best option would be for the initial reaction to come from the person that posted the poll not from the person that added the integration? The person that posted the poll is really trying to gather the opinions of other people so they ought to not vote anyway.

**Comment by leifhanack** [comment]
@nicgordon As the person who posted the poll I want to participate as well. My 'workaround' is to create another user (myslackadmin) and let him install simple-poll. After that everything is fine.

**Comment by wilhelmklopp** [comment]
@nicgordon Yes, this is an awesome suggestion and one that I had hoped to include as well when the first version of Simple Poll was built.

The problem here is that to get permission from Slack to add reactions to a message on behalf of a user, this user needs permission to install slack apps (ie be an admin on the Slack team) and then subsequently install Simple Poll.
That means for this to work in the way you described, every user would have to re-install Simple Poll before they could create a poll with emoji reactions coming from them. Not only is this super inconvenient, but also in most teams there are only few people who have sufficient privileges to install slack apps.

So unfortunately, making this work in practice is not really feasible...

Having said that, I _do_ believe that there will be a fix for this from Slack's side in the near future.

Until then, workarounds like the one suggested by @leifhanack are the best way forward _for now_.

**Comment by sebinievas** [comment]
Could the poll, upon creation, remove the reactions or simulate that click? Haven't looked deep into this so just seeing what sticks.

**Comment by wilhelmklopp** [comment]
@sebinievas remove the reactions at what point? Right after it was created?

**Comment by sebinievas** [comment]
Yeah like to zero it out. Then it will appear as though it started without
initial votes. I might be left field here.

**Comment by wilhelmklopp** [comment]
@sebinievas Oh, in that case the reactions would just disappear unfortunately. Slack automatically hides any reaction with count 0. 😄

**Comment by sebinievas** [comment]
Ah yep. Good call

**Comment by wilhelmklopp** [comment]
Closing this because button polls are out of beta and fully ready for use 😃
