### ISSUE TITLE
Created a "Service account" to do the polls, not working

### ISSUE THREAD

**Issue by jdell64** [xoneco/simple-poll#30]
I installed simple-poll on with my account a while ago. Things were working, but I was getting annoyed at not being able to vote (this issue is already mentioned).

I created a new email account and joined the slack team. I uninstalled then reinstalled using that neutral account. Now, whenever I try to do a poll, I get:

```
Simple Poll cannot add emoji to polls in this channel. Sorry about that :disappointed:
```

can I do anything about that?

**Comment by wilhelmklopp** [comment]
Hey!

I'd suggest using button polls!
They will fix problems like these :)

You can enable them in the dashboard settings: https://simplepoll.rocks/dashboard/
