### ISSUE TITLE
Poll buttons are disappearing

### ISSUE THREAD

**Issue by Zhomart** [xoneco/simple-poll#32]
When I click on buttons, they disappear. Happens to all in our team.

Here is the screenshot:

![http://i.imgur.com/2ZCfk5P.gif](http://i.imgur.com/2ZCfk5P.gif)

**Comment by wilhelmklopp** [comment]
Duplicate of #3 

If you enable button polls in the dashboard settings, this problem will go away :)

https://simplepoll.rocks/dashboard/
