### ISSUE TITLE
My vote is casted by Default whenever they create a simple poll

### ISSUE THREAD

**Issue by subasv** [xoneco/simple-poll#33]
I wasn't part of a slack channel but in a Simple poll created there has 4 options and my name is shown in that four options like i have casted the vote!! My team tried creating a poll in the channel I am in and even in that all options has my vote by default!! Why is this? This creates a lot of confusion in those channels which doesn't know who I am!!

Please fix this.

Thanks,
Suba

**Comment by wilhelmklopp** [comment]
If you enable button polls in the dashboard settings, this problem should go away: https://simplepoll.rocks/dashboard/

:)
