### ISSUE TITLE
Poll option numbers not showing on buttons in slack Android app

### ISSUE THREAD

**Issue by pinki3** [xoneco/simple-poll#36]
I created a poll in the Android app just now. The numbers did not show on the buttons themselves. No issue viewing the poll on desktop.
 Using v 2.34.0-4877 on Android nougat. 
On andriod:
![36-android](https://cloud.githubusercontent.com/assets/6010328/26024808/ee7adabc-37d9-11e7-88aa-53661af176ab.png)
On desktop (linux):
![36-desktop](https://cloud.githubusercontent.com/assets/6010328/26024809/f16adcfe-37d9-11e7-8c70-d5536f97a648.png)

**Comment by wilhelmklopp** [comment]
This is an bug in the Slack android app. They're aware of it and working on fixing it :)

**Comment by pinki3** [comment]
Oh, I suspected that :) Great! 
Closing the issue then.
