### ISSUE TITLE
Respect profile setting to show real names instead of usernames

### ISSUE THREAD

**Issue by aeyaey** [xoneco/simple-poll#38]
When users votes, their usernames is listed below the voted option.
I have enabled the slack message display configuration: "Display real names instead of usernames". I expected simple-poll would respect this.

**Comment by wilhelmklopp** [comment]
Implementing this would actually be much harder to do. When a user clicks a button, Slack sends the username, but not the full name. Details here: https://api.slack.com/docs/message-buttons

It would likely require more API calls and additional OAuth scopes, so unfortunately this is a `wontfix` for now.
