### ISSUE TITLE
List of polls in dashboard shows private polls

### ISSUE THREAD

**Issue by binaryben** [xoneco/simple-poll#41]
I think this is a bug. The admin shouldn't be able to see polls they weren't privy to when used in a DM.

EDIT: having seen that settings are user by user, it may be that I can only see my recent polls. This does seem to beg the question though why isn't there global settings for admin instead?

**Comment by wilhelmklopp** [comment]
Hi @BinaryBen You will only see polls that you yourself created, not anyone else on the team.
