### ISSUE TITLE
Should allow any emoji to be used to vote instead of 1️⃣2️⃣etc

### ISSUE THREAD

**Issue by dgpokl** [xoneco/simple-poll#43]
it could be that if the first character of any option is an emoji, use that as the emoji for the vote buttons.

**Comment by wilhelmklopp** [comment]
👋 You can already do this using the following syntax:

`/poll "Poll question?" "Option 1" :simple_smile: "Option 2" "Option 3"`
It'll create a poll that looks like this:
![image](https://user-images.githubusercontent.com/7718702/42135204-71eefc42-7d3f-11e8-9f93-4c0131befd52.png)
