### ISSUE TITLE
Add option after poll has been created

### ISSUE THREAD

**Issue by tnguyen14** [xoneco/simple-poll#6]
Is it feasible to consider a feature to add an option after the poll has been created?

I'm seeing this since after someone creates a poll, others chime in to suggest more options.

**Comment by wilhelmklopp** [comment]
This would be possible, but I feel it adds a layer of complexity to the User Experience that makes the overall experience less _simple_. 
In fact, it might even be simpler to discuss the options you want on the poll and then create a new one?

Would love to hear some more feedback on this :)

Either way I'm always happy for anybody to fork this and add to it. It's actually really easy to self-host with Heroku.

**Comment by tnguyen14** [comment]
I was just thinking of something as simple as editing the message like the way it is currently done with regular messages. But because the message is posted by the bot, the poll owner isn't able to edit it. Is it possible to post the poll as the user instead?

**Comment by wilhelmklopp** [comment]
Not without every user individually giving permissions, which would be super inconvenient. :(
