### ISSUE TITLE
Private Channel - poll creation fails

### ISSUE THREAD

**Issue by beahnomad** [xoneco/simple-poll#8]
Slack, Mac desktop app v1.1.8 (3052)
- open private channel
- invite people
- use "/poll" to start a simple poll

ACTUAL: poll creation fails (see attachment)
EXPECTED: poll should be successfully created
<img width="1022" alt="screen shot 2016-01-14 at 08 56 08" src="https://cloud.githubusercontent.com/assets/10979943/12322388/149905a6-bab4-11e5-8d08-8d61a05a098a.png">

**Comment by wilhelmklopp** [comment]
OK, I have tried to replicate this, and I think this occurs when you try to create a poll in a private channel (or an MPIM), that the user which installed Simple Poll is not a part of.

At the moment I cannot fix this, but I have reached out to the Slack API developers to see why this functionality exists for Instant Messages (IMs), but not for Multi Party Instant Messages (MPIMs) or private channels.

More information on the problem here: https://api.slack.com/methods/chat.postMessage

**Comment by beahnomad** [comment]
You're right. I just tried to create a poll in a MPIM in which the user who installed Simple Poll is part of - and it worked :)

**Comment by wilhelmklopp** [comment]
OK, just heard back from the Slack guys. They think this is a bug on their side and will look into it. This should start working automatically once they have implemented the additional functionality.

I will keep this open until it works. 
Thanks for the bug report :)

**Comment by m8ryx** [comment]
looks like this is still an issue, and we've run several tests on how it works.  The emojis are created as the user who performed the integration.  This is overridden if a new user performs the integration again.  It _appears_ that the poll itself is created by Simple Poll.

I do really appreciate your low-information design decision, which makes this the most appealing polling solution for our corporate Slack.  Do you have a link to the open issue w/in Slack?  I can attempt to escalate it through our service contract.  Thanks for creating this sleek and thoughtful tool.

**Comment by m8ryx** [comment]
wondering if the as_user flag (documentation says it default to false) could be explicitly set to false for the posting?  Perhaps the documentation is incorrect, else it may require that a bot integration is in place.

**Comment by wilhelmklopp** [comment]
Update on this:
This is _not_ a bug on Slack's side of things, but rather intended behavior. I have asked them to add a small additional feature to the Slash Command Delayed response endpoint, which should make this problem go away. Fingers crossed that it will be implemented.

@m8ryx You seem to be referring to #3. Is that correct? I can confirm that the message is created by Simple Poll, but that the emoji reactions come from the user in the way you described. This is currently the only way possible. More info [here](https://api.slack.com/methods/reactions.add), but this is related to #3.

**Comment by wilhelmklopp** [comment]
Made some changes that fixes this issue to some extent. You will still have to add emoji reactions to the message yourself, but at least now the poll will actually be created.
